### ISSUE TITLE
Examples Request

### ISSUE THREAD

**Issue by devinci** [juliuscc/semantic-release-slack-bot#61]
Please provide usage examples for the options provided. Trying to integrate this into my build and adjust the slackWebhook env variable to what I have declared in my CI, but am uncertain as to the format it requires.

**Comment by hannesrabo** [comment]
I'm not sure if I completely understand your question, but I will try to answer it anyways. Please add some more description otherwise.

If you want to add the `SLACK_WEBHOOK` the easy way, you just add this into your environment as you normally do to expose things in your CI environment.

Something like

```bash
[export] SLACK_WEBHOOK="https://the-link-you-have"
```

If you already have a variable that contains this webhook link you can change where it is read from.

Just add the variable `slackWebhookEnVar` to the plugin config just as the example in the documentation here: https://github.com/juliuscc/semantic-release-slack-bot#function shows it for `notifyOnSuccess`

You can set it to something like:
```js
{
    slackWebhookEnVar: "ALREADY_EXISTING_ENV_VAR",
    ...
}
```

**Comment by devinci** [comment]
I already have a webhook declared.

>{
    slackWebhookEnVar: "ALREADY_EXISTING_ENV_VAR",
    ...
}

I did attempt to do that, however the build output when overwriting the env resulting in it requiring the declaration for the slackWebhook:
![image](https://user-images.githubusercontent.com/7167770/104941560-e626f000-59bb-11eb-8ff7-5fd3e69f2530.png)

After I declared the slackWebhook the to same env var it resulted in a request for a package name declaration, which should just use the npm package as far as the instructions outline?
![image](https://user-images.githubusercontent.com/7167770/104941823-3c942e80-59bc-11eb-9c84-0f3dc4901c92.png)

**Comment by BeyondEvil** [comment]
> "slackWebhook": "SLACK_WEBHOOK_URL"

If I'm not mistaken, if you remove the above line, it should work.

Given there exists a environment variable called `SLACK_WEBHOOK_URL` that contains the Slack webhook URL.

**Comment by juliuscc** [comment]
I agree with BeyondEvil's proposed solution. This seems solved to me so I will close it, but feel free to open it if you still have problems 😁

**Comment by devinci** [comment]
Sorry for the delay in response, busy week. 

@BeyondEvil In my original post I did mentioned that I attempted that, which resulted in the CLI output in the first image, and then when I defined the "slackWebhook" as seen in that chunk I outlined (which didn't have it in before), the CLI output was the second image.

I am able to reference the same environment variable using another library via ` ${{ secrets.SLACK_WEBHOOK_URL }}` so I've resorted to using that library that for now. 

Appreciate the help though.
