### ISSUE TITLE
In the slack generated GitLab tag link is wrong!

### ISSUE THREAD

**Issue by Y-Hovo** [juliuscc/semantic-release-slack-bot#82]
In the slack GitLab tag link generation code below:
file: lib/success.js 
code: `/releases/tag/${gitTag}|${gitTag}>` - line 105

link must be: `${repo.URL}/-/releases#${gitTag}|${gitTag}`  or `${repo.URL}/-/tags/${gitTag}|${gitTag}`.
Link return 404 Not Found.
<img width="742" alt="Screen Shot 2021-12-24 at 16 08 04" src="https://user-images.githubusercontent.com/89020996/147352018-9d304574-68e8-4856-8b0c-ad8d5a770128.png">
Thanks.

**Comment by juliuscc** [comment]
Thanks for the issue!

Am I understanding correctly that the link is incorrectly created when you use the default behaviour? What would you expect the link to look like and how is it actually?

Do you use gitlab cloud or on-prem?

**Comment by tgrafford** [comment]
We're using BitBucket (on-prem) and we're having the same issue.

Generated link is: https://{{host}}/7999/{{bitbucket_project}}/{{bitbucket_repo}}/releases/tag/{{version}}
Expected link is: https://{{host}}/stash/projects/{{bitbucket_project}}/repos/{{bitbucket_repo}}/browse?at=refs%2Ftags%2F{{version}}

We are also having issues with the comparison link ("1.0.9 (2021-12-24)" in the image above) as the %-signs get encoded into %25, causing an invalid url.

It would be great if these links could be configurable with some templating support.

**Comment by juliuscc** [comment]
Okay, I have a couple of follow-up questions just so that we get this right:
- You provide different URLs. Is there a difference between On-Prem vs Cloud or is there another reason for the URLs to be different?
- I thought you wanted the %-signs to be URL-encoded like the rest. Why should it not be URL-encoded?
- Could you give an example of a URL with the %-signs?
- Is there any difference between tagged versions/releases/PRs in Bitbucket? What would you think is the best place to point the URL? Is it a tag or maybe a specific commit?

I would love a PR for solving this. It would help if you could develop it yourself so that you can test that it works properly for your workflow.

Lastly, if this has to be resolved quickly I recommend you use templates for the full message. We don't support templating for just the URL but I don't think that is a good feature to add, as we already support full templating of the full message. What do you think about that as a temporary workaround before we fix the root issue?

**Comment by tgrafford** [comment]
1. The two URLs I provided are; 
    - The actual URL generated by `semantic-release-slack-bot`
    - The expected URL to get to the desired view in BitBucket
2. Our `compareUrlFormat` already contains URL encoded characters. It looks something like this;
    `[..]/compare/commits?targetBranch=refs%2Ftags%2F{{previousTag}}&sourceBranch=refs%2Ftags%2F{{currentTag}}`
    This generates a valid URL in our CHANGELOG.md.
3. The generated URL in slack for OPs example would look like this for us: 
    `[..]/compare/commits?targetBranch=refs%252Ftags%252Fv1.0.8&sourceBranch=refs%252Ftags%252Fv1.0.9`
    Note that `%2F` gets escaped to `%252F`.
4. The best place to point the URL is to the tag, as already implemented. It's just the URL that needs tweaking.

I know of the templating functionality using JS. However, we're already using `.releaserc.json` for configuring `semantic-release`, and I'm not that keen on adding more configuration files to that lib. Its not that big of a deal for us, the plugin works as expected, its just the URLs that don't. :)

Thanks anyway for a great plugin!

**Comment by juliuscc** [comment]
Is your expected link the same as:
> `${repo.URL}/-/releases#${gitTag}|${gitTag}` or `${repo.URL}/-/tags/${gitTag}|${gitTag}`
which @Y-Hovo listed in the top of this PR? To me they look different.

Do I understand the url-encoding issue correctly as semantic-release generates a correctly url-encoded URL, and then this library url-encodes it again when sending the message to Slack? I am trying to figure out where the double encoding happens.

**Comment by fmigot** [comment]
Hi there :)

I'm facing the same issue with the **default template generated**: the tag link you're building line 105 is wrong as @Y-Hovo mentioned.
A 404 is retuned instead of either **the tag page** `${repo.URL}/-/tags/${gitTag}|${gitTag}` or **the release note page** with an anchor to the tag `${repo.URL}/-/releases#${gitTag}|${gitTag}`.

Could you provide a little fix by providing one of the two possible urls?

Thanks for you plugin, that's perfect🤘!

**Comment by juliuscc** [comment]
I welcome a PR that fixes this. I still don't understand if it's just about changing the URL, or if there is something that has to change with URL encoding.

**Comment by fmigot** [comment]
Hello,

Can you add me as a collaborator please so I can create a PR.

Thanks!
<img width="1140" alt="Capture d’écran 2022-01-26 à 20 13 24" src="https://user-images.githubusercontent.com/15667911/151231160-c918f71f-d95d-43ea-a109-17edc1be92f5.png">

**Comment by juliuscc** [comment]
Hi @fmigot! You can create PR's without being a collaborator. Start by forking this repo, and then do any changes you want in your fork. Then you can follow [these instructions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) to submit a PR.

**Comment by juliuscc** [comment]
I closed this issue cause the main issue is solved. If you still have issues with URL-encoding @tgrafford please open a new issue and we can take it from there 😁

**Comment by morewings** [comment]
We still have old URLs with `3.5.2` version. `https://git.naspersclassifieds.com/olxeu/pwa/shared/olx-ui-library/releases/tag/v10.0.0`

**Comment by rolandjitsu** [comment]
I'm actually having the same issue, but https://github.com/juliuscc/semantic-release-slack-bot/pull/90 does not fix instances where we use self hosted GitLab.
